apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres-hl
  namespace: airflow
spec:
  clusterIP: None
  selector:
    component: airflow
    name: postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-postgresql
  namespace: airflow
spec:
  serviceName: airflow-postgres-hl
  replicas: 1
  selector:
    matchLabels:
      component: airflow
      name: postgresql
  template:
    metadata:
      name: airflow-postgresql
      labels:
        component: airflow
        name: postgresql
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: servers.com/label
      #               operator: In
      #               values:
      #                 - "bright-stream-k8s-was1-node-13"
      containers:
        - name: postgresql
          image: postgres:13@sha256:4c5c343b5c700d60870e852bcc78be442e15f56419b9055181f3ce4622b5a1a8
          env:
            - name: POSTGRES_USER
              value: "airflow"
            - name: POSTGRES_DB
              value: "airflow"
            - name: POSTGRES_PASSWORD
              value: "airflow"
            - name: PGDATA
              value: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "airflow" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "airflow" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: airflow-pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: airflow-pg-data
      spec:
        storageClassName: openebs-lvm-ssd-prod-xfs-shared
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
